# Quick Guide

This page is a practical overview of the main things people do with `toytree`: parse trees, inspect their data, select nodes, modify topology, draw figures, and save results. Use it to get oriented quickly, then follow the links to the more focused guides when you want more detail.

Useful next stops: [parsing tree data](parse_trees.md), [drawing basics](drawing-basics.md), [writing tree data](write_trees.md), and [command line usage](command-line.md).

## The `toytree` package
`toytree` is a Python library for working with trees as data structures. Most workflows start with a `ToyTree` object: you load tree data, inspect or store features on nodes, modify the tree, and then draw or export the result.

`toytree` works especially well in Jupyter notebooks because tree drawings display inline and remain easy to style in code. This guide is notebook-based, so you can follow it from top to bottom in your own session if you want to try the examples interactively.

To begin, let's import the package.

In [1]:
import toytree

toytree.__version__

'3.1.0.dev0'

## A simple example
This short example shows a common `toytree` workflow: parse a tree, reroot it, and draw it. The tree is loaded with `toytree.tree()`; for a broader overview of accepted input types and formats, see [parsing tree data](parse_trees.md).

The example below reads from a public URL, so it requires internet access. The call to `.root("~prz")` uses a regular-expression query to choose an edge based on matching names, which is covered in more detail in [node query and selection](core-query.md).

Finally, `.draw()` renders the tree in the notebook output. Here the tip labels are aligned and node hover tooltips are enabled, but the same method can also be used for simpler static drawings or more customized figures. See [drawing basics](drawing-basics.md) for the main drawing workflow.

In [2]:
# load a toytree from a newick string at a URL
utree = toytree.tree("https://eaton-lab.org/data/Cyathophora.tre")

# re-root on internal edge selected using a regex string
rtree = utree.root("~prz")

# draw the rooted tree
rtree.draw(node_hover=True, node_sizes=8, tip_labels_align=True);

## Parsing tree data
`toytree.tree()` is the main entry point for loading one tree. It accepts tree text, file paths, URLs, and bytes, and it can parse Newick, NHX-style metadata, and NEXUS containers. The dedicated guide in [parsing tree data](parse_trees.md) covers those formats in more detail.

In the example below, a Newick string is parsed into a `ToyTree`, and `get_node_data()` is used to inspect what was stored on each node. This is often the quickest way to confirm how tip names, branch lengths, and internal support values were interpreted.

In [3]:
# newick str with edge-lengths & support values
newick = "((a:1,b:1)90:3,(c:3,(d:1,e:1)100:2)100:1);"

# load as ToyTree
tree = toytree.tree(newick)

# show tree data parsed from Newick str
tree.get_node_data()

   idx name  height  dist  support
0    0    a     0.0   1.0      NaN
1    1    b     0.0   1.0      NaN
2    2    c     0.0   3.0      NaN
3    3    d     0.0   1.0      NaN
4    4    e     0.0   1.0      NaN
5    5          1.0   3.0     90.0
6    6          1.0   2.0    100.0
7    7          3.0   1.0    100.0
8    8          4.0   0.0      NaN

Once a tree is parsed, its stored features can be used directly in a drawing. In the example below, `node_labels="idx"` writes each node's cached index, and `edge_colors="dist"` maps branch lengths to colors automatically. This is usually safer and clearer than trying to keep separate style lists in the correct node order. See [data and features](core-data.md) for more detail.

In [4]:
# tree drawing showing Node idx labels and edges colored by dist
tree.draw(
    layout="d",
    node_labels="idx",
    node_sizes=15,
    node_mask=False,
    node_colors="lightgrey",
    edge_colors="dist",
    edge_widths=3,
    tip_labels_style={"font-size": 20, "anchor-shift": 20},
    scale_bar=True,
);

## Class objects

The core `toytree` objects form a simple hierarchy. A [`Node`](node.md) stores local tree data and relationships. A collection of connected nodes is wrapped by a [`ToyTree`](tree.md), which is the main object most users work with. A collection of trees can then be grouped into a [`MultiTree`](multitree.md).

You do not need to memorize the full class structure to get started. In practice, most work begins with a `ToyTree`, and `Node` or `MultiTree` objects become important when you need direct access to one part of a tree or to many trees at once.

**Node**: See the [Node class](core-node.md) docs for the full API. In everyday use, you usually reach `Node` objects by indexing or traversing a tree. Nodes store local information such as names, distances, and any extra features you assign. Each node in a `ToyTree` also has an `idx` value that reflects the tree's cached traversal order; see [traversal and node selection](core-traversal.md) for more on that.

In [5]:
# you can create a Node object on its own
toytree.Node(name="X")

In [6]:
# but more often you will select Nodes from a tree by slicing or indexing
tree[0]

In [7]:
# a Node's parent is at .up
tree[0].up

In [8]:
# a Node's children are at .children
tree[5].children

(<Node(idx=0, name='a')>, <Node(idx=1, name='b')>)

In [9]:
# select one or more Nodes from a ToyTree by name
tree.get_nodes("a", "c")

In [10]:
# access data from attributes of a Node in a ToyTree
tree[0].idx, tree[0].name, tree[0].dist

(0, 'a', 1.0)

**ToyTree**: See the [ToyTree class](core-toytree.md) docs for the full API. `ToyTree` is the main container for a connected set of nodes and the object you will usually pass around in analysis and plotting code. It caches useful derived information such as node heights, tip counts, and traversal order, while also exposing methods for rooting, pruning, editing data, and drawing. If a structural operation changes the tree, the cached view is rebuilt automatically.

In [11]:
# create a tree from a Node object to serve as its root Node
toytree.ToyTree(toytree.Node("root"))

In [12]:
# parse a tree from newick data
toytree.tree("((a,b),c);")

In [13]:
tree.ntips

5

In [14]:
tree.nnodes

9

In [15]:
tree[5].height

1.0

In [16]:
# all nodes in the cached idx order (tips first then postorder traversal)
tree[:]

[<Node(idx=0, name='a')>,
 <Node(idx=1, name='b')>,
 <Node(idx=2, name='c')>,
 <Node(idx=3, name='d')>,
 <Node(idx=4, name='e')>,
 <Node(idx=5)>,
 <Node(idx=6)>,
 <Node(idx=7)>,
 <Node(idx=8)>]

In [17]:
# or, use .traverse() to visit Nodes in other traversal orders
list(tree.traverse("postorder"))

[<Node(idx=0, name='a')>,
 <Node(idx=1, name='b')>,
 <Node(idx=5)>,
 <Node(idx=2, name='c')>,
 <Node(idx=3, name='d')>,
 <Node(idx=4, name='e')>,
 <Node(idx=6)>,
 <Node(idx=7)>,
 <Node(idx=8)>]

**MultiTree**: See the [MultiTree docs](core-multitree.md) for the full API. A `MultiTree` stores multiple `ToyTree` objects together so you can compare, summarize, or draw them as a set. The `toytree.mtree()` function parses multi-tree inputs, and `toytree.MultiTree()` can also be built from a collection of existing trees.

In [18]:
# create a MultiTree containing three copies of 'tree' rooted differently
mtree = toytree.mtree([tree, tree.root("c"), tree.root("d", "e")])
mtree

In [19]:
# select individual ToyTrees by indexing or slicing
mtree[0]

In [24]:
# visualization methods for multiple trees. Takes similar arguments as ToyTree.draw()
mtree.draw(shape=(1, 3), tip_labels_style={"font-size": 16});

## Learning to use `toytree`

One of the fastest ways to learn `toytree` is to explore objects interactively in Jupyter or an IDE with tab completion. A `ToyTree` exposes many attributes and methods, and seeing them in context is often more useful than reading a long reference page from top to bottom.

In a notebook, type a variable name such as <i>tree</i>, add a dot, and press <kbd>tab</kbd> to inspect the available methods. A few examples are shown below.

In [25]:
tree.copy()

In [26]:
tree.is_rooted()

True

In [27]:
tree.is_monophyletic("a", "b")

True

In [28]:
tree.get_ancestors("a")

{<Node(idx=0, name='a')>, <Node(idx=5)>, <Node(idx=8)>}

In [29]:
tree.get_mrca_node("d", "e")

In [30]:
tree.get_tip_labels()

['a', 'b', 'c', 'd', 'e']

## Selecting nodes
Many tree operations need one or more nodes as input. `toytree` tries to make that practical by allowing selection by name, regular expression, integer `idx`, or MRCA queries instead of forcing you to rely on one fragile indexing scheme.

The examples below use `get_nodes()` and `get_mrca_node()`, which cover most everyday selection tasks. The fuller selection guide is [node query and selection](core-query.md).

In [31]:
# select nodes by name
tree.get_nodes("a", "b")

In [32]:
# select nodes by regular expression
tree.get_nodes("~[a-c]")

In [33]:
# select internal node by mrca of tip names
tree.get_mrca_node("a", "b")

In [34]:
# or, select a node directly by its idx label
tree[5]

## Subpackages
The `ToyTree` object is intentionally kept focused on the most common tree operations. More specialized algorithms live in subpackages such as `rtree`, `mod`, `distance`, `annotate`, and `pcm`. This keeps the main object easier to explore while still making the broader toolkit available when you need it.

The examples below are only a brief orientation. Treat this section as a map of where to look next, not as a full tour of each subpackage.

**rtree**: Random tree generation functions. Use `rtree` when you need small example trees, test data, or simulated topologies for an analysis workflow.

In [35]:
# generate a birth-death tree
btree = toytree.rtree.bdtree(ntips=8, b=1, d=0.1, seed=123, random_names=True)
btree.draw(scale_bar=True);

**enum**: enumeration of tree data. Use `enum` when you need exact sets of tree-derived objects such as quartets or bipartitions, often for testing or algorithm development.

In [36]:
# expand a generator over all quartets in a tree
list(toytree.enum.iter_quartets(tree))

[({'a', 'b'}, {'c', 'e'}),
 ({'a', 'b'}, {'c', 'd'}),
 ({'a', 'b'}, {'d', 'e'}),
 ({'d', 'e'}, {'b', 'c'}),
 ({'d', 'e'}, {'a', 'c'})]

**distance**: node and tree distance metrics. Use `distance` to measure paths within one tree or to compare the similarity of two trees.

In [37]:
# return a matrix of distances between tips in a tree
toytree.distance.get_tip_distance_matrix(tree, df=True)

     a    b    c    d    e
a  0.0  2.0  8.0  8.0  8.0
b  2.0  0.0  8.0  8.0  8.0
c  8.0  8.0  0.0  6.0  6.0
d  8.0  8.0  6.0  0.0  2.0
e  8.0  8.0  6.0  2.0  0.0

In [38]:
# return the Robinson-Foulds tree distance between two random 10-tip trees
rtree1 = toytree.rtree.rtree(10, seed=123)
rtree2 = toytree.rtree.rtree(10, seed=321)
toytree.distance.get_treedist_rf(rtree1, rtree2, normalize=True)

0.42857142857142855

**mod**: Tree modifications. Use `mod` for tree-editing operations such as rerooting, pruning, rescaling branch lengths, or changing topology.

In [49]:
# return a tree with edges scaled so root is at height=100
modified = toytree.mod.edges_scale_to_root_height(tree, 100)

# show the original and modified trees side by side
toytree.mtree([tree, modified]).draw(
    shape=(1, 2), scale_bar=True, tip_labels_style={"font-size": 15}
);

In [50]:
# return a tree with a new split (internal node and child) added
modified = toytree.mod.add_internal_node_and_child(tree, "d", name="x")

# show the original and modified trees side by side
toytree.mtree([tree, modified]).draw(shape=(1, 2), tip_labels_style={"font-size": 15});

**annotate**: add annotations to tree drawings. Use `annotate` when you want to add labels, markers, bars, or other extras after the initial `draw()` call.

In [54]:
# draw a tree and store returned objects
canvas, axes, mark = tree.draw()

# annotate method to add node markers
toytree.annotate.add_tip_markers(tree, axes, color="salmon", size=12)

# annotate method to add to edge labels
toytree.annotate.add_edge_labels(
    tree, axes, labels="idx", font_size=15, yshift=-12, mask=False
);

**pcm**: phylogenetic comparative methods. This subpackage currently includes simulation and model-fitting tools for discrete and continuous traits, and it is the place to look when your tree is part of a comparative analysis.

In [55]:
# get variance-covariance matrix from tree
toytree.pcm.get_vcv_matrix_from_tree(tree, df=True)

     a    b    c    d    e
a  4.0  3.0  0.0  0.0  0.0
b  3.0  4.0  0.0  0.0  0.0
c  0.0  0.0  4.0  1.0  1.0
d  0.0  0.0  1.0  4.0  3.0
e  0.0  0.0  1.0  3.0  4.0

In [56]:
# simulate a discrete trait under a Markov transition model
toytree.pcm.simulate_discrete_trait(tree, nstates=3, model="ER", nreplicates=5)

  t0 t1 t2 t3 t4
0  2  0  1  2  1
1  0  0  1  0  0
2  0  0  0  0  2
3  2  1  2  1  0
4  0  1  0  1  1
5  1  0  1  2  0
6  0  1  0  1  1
7  2  2  0  0  2
8  0  0  2  0  2

## Storing data to trees
Trees often need more than topology and branch lengths. `toytree` lets you attach arbitrary features to nodes, either by assigning attributes directly or, more commonly, by using `set_node_data()` to update many nodes at once.

After adding data, `get_node_data()` is the quickest way to inspect what is present across the full tree. The examples below show a few common patterns: setting one default for all nodes, setting one value for tips and another for internal nodes, and leaving some nodes missing.

In [57]:
# make a copy of tree on which we will add a bunch of data
dtree = tree.copy()

# add a feature and set all Nodes to a default value
dtree = dtree.set_node_data("trait1", default=10)

# or set some to specific values and others to a default
dtree = dtree.set_node_data("trait2", {i: 5 for i in range(dtree.ntips)}, default=1)

# or add some to specific values and leave others as NaN
dtree = dtree.set_node_data("trait3", {0: "X", 1: "Y"})

# or, add a feature by assigning as an attribute to one or more Nodes
dtree[6].trait4 = "special"

# show the data
dtree.get_node_data()

   idx name  height  dist  support  trait1  trait2 trait3   trait4
0    0    a     0.0   1.0      NaN      10       5      X      NaN
1    1    b     0.0   1.0      NaN      10       5      Y      NaN
2    2    c     0.0   3.0      NaN      10       5    NaN      NaN
3    3    d     0.0   1.0      NaN      10       5    NaN      NaN
4    4    e     0.0   1.0      NaN      10       5    NaN      NaN
5    5          1.0   3.0     90.0      10       1    NaN      NaN
6    6          1.0   2.0    100.0      10       1    NaN  special
7    7          3.0   1.0    100.0      10       1    NaN      NaN
8    8          4.0   0.0      NaN      10       1    NaN      NaN

## Tree drawings
When you call `.draw()` on a tree it returns three objects: a Canvas, Cartesian axes, and a Mark. This follows the structure of the [Toyplot documentation](https://toyplot.readthedocs.io/) because `toytree` uses Toyplot as its default drawing backend. The canvas holds the figure, the Cartesian object controls the coordinate system, and the mark represents the tree itself.

You can ignore those return values for quick plots, but they become useful when you want to add annotations, adjust axes, or save figures with more control.

In [58]:
# the draw function returns three objects
tree.draw()

(<toyplot.canvas.Canvas at 0x74efcadc8170>,
 <toyplot.coordinates.Cartesian at 0x74efcad1d940>,
 <toytree.drawing.src.mark_toytree.ToyTreeMark at 0x74efcadbc3e0>)

Many drawing calls here end with a semicolon. In a notebook this simply hides the textual return value so the rendered figure is easier to read. The figure still displays normally, and if you save the notebook the output is saved with it.

In [59]:
# the semicolon hides the returned text of the Canvas and Cartesian objects
tree.draw();

You can also keep the returned objects and edit them after the initial draw call. This is useful when the main tree layout is correct but you want to tune labels, axes, or other presentation details.

In [60]:
# or, we can store them as variables
canvas, axes, mark = tree.draw(scale_bar=True)

# and then optionally add additional styling
axes.x.label.text = "Time (Mya)"
axes.x.label.style["font-size"] = 14
axes.x.label.offset = 20

## Styling tree drawings
You can style drawings one option at a time, or start from a built-in tree style and then adjust individual settings. The second approach is often easier when you want a coherent look without writing every style argument from scratch.

The examples below show both patterns. For more focused drawing guides, see [drawing basics](drawing-basics.md).

In [61]:
# drawing with pre-built tree_styles
tree.draw(tree_style="c")  # coalescent-style
tree.draw(tree_style="d")  # dark-style

# 'ts' is also a shortcut for tree_style
tree.draw(ts="o");  # umlaut-style

In [62]:
# define a style dictionary
mystyle = {
    "layout": "d",
    "edge_type": "p",
    "edge_style": {
        "stroke": "darkcyan",
        "stroke-width": 2.5,
    },
    "tip_labels_colors": "black",
    "tip_labels_style": {"font-size": "16px"},
    "node_sizes": 8,
    "node_colors": "dist",
    "node_labels": "support",
    "node_labels_style": {"baseline-shift": 12, "anchor-shift": 15, "font-size": 12},
    "node_mask": (0, 1, 0),
}

# use your custom style dictionary in one or more tree drawings
tree.draw(height=300, **mystyle);

## Saving tree drawings
Figures can be saved as HTML, SVG, PDF, or PNG. In most cases `toytree.save()` is the easiest entry point because the output format is inferred from the file suffix. SVG is the most faithful vector output for further editing, while PDF and PNG are convenient final export formats.

For PDF and PNG, `toytree.save()` now prefers CairoSVG when it is installed and otherwise falls back to the older ReportLab backend. You can also control raster and page export with options such as `backend`, `dpi`, `scale`, `background_color`, `output_width`, and `output_height`.

In [63]:
# draw a plot and store the Canvas object to a variable
canvas, axes, mark = tree.draw(ts="p")

HTML is the default save format. It preserves vector graphics and can also preserve interactive behavior, which makes it a good choice for sharing in a browser or embedding on a website.

In [64]:
# HTML allows for interactivity and embedding in web sites
toytree.save(canvas, "/tmp/tree-plot.html")

In [65]:
# SVG for figures you will further edit in Illustrator/Inkscape
toytree.save(canvas, "/tmp/tree-plot.svg")

In [66]:
# PDF for shareable figures; backend can be selected explicitly
toytree.save(canvas, "/tmp/tree-plot.pdf", backend="cairosvg", background_color="white")

In [67]:
# PNG for slides or web use, with explicit raster sizing
toytree.save(canvas, "/tmp/tree-plot.png", output_width=1600, dpi=300)

Toyplot also exposes lower-level save functions. `toytree.save()` is mainly a convenience wrapper around that functionality, but it also handles the CairoSVG PDF/PNG conversion path and backend fallback logic for common export workflows.

In [68]:
import toyplot

toyplot.html.render(canvas, "/tmp/tree-plot.html")

In [69]:
import toyplot.svg

toyplot.svg.render(canvas, "/tmp/tree-plot.svg")

In [70]:
import toyplot.pdf

toyplot.pdf.render(canvas, "/tmp/tree-plot.pdf")

In [71]:
import toyplot.png

toyplot.png.render(canvas, "/tmp/tree-plot.png")